language: go

go:
  - "1.10.x"

sudo: required

services:
  - docker

install:

jobs:
  include:
    - stage: Pre-build
      install: skip
      script:
      - go get -u github.com/kardianos/govendor
      - cd go
      - govendor sync -v
    - stage: Test
      install: skip
      script:
      - cd go
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic
    - stage: Build
      install: skip
      script:
      - cd go
      - go build -v ./...
    - stage: Build
      install: skip
      script:
      - docker build .
