

go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master

sudo: required

services:
  - docker

install:

jobs:
  include:
    - stage: aa
      script:
      - echo aa 1
      - go version
    - stage: aa
      script:
      - echo aa 2
      - go version
    - stage: bb
      script:
      - echo bb 1
      - go version