
go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master

sudo: required

services:
  - docker

jobs:
  include:
    - stage: aa
      script: echo aa 1
    - stage: aa
      script: echo aa 2
    - stage: bb
      script: echo bb